version: "3.7"

services:
  web:
    image: go-docker-webserver
    build: .
    ports:
      - "5000:5000"
    # networks: s2l_network
    depends_on: [es01,]

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      xpack.security.enabled: "false"
      discovery.type: single-node
      # networks: s2l_network
    ports:
      - 9200:9200
      - 9300:9300

    command: >
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment 
      || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment; 
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.0.0
      environment:
        - ELASTICSEARCH_HOSTS=http://es01:9200
      ports:
        - 5601:5601
      depends_on:
        - es01
# networks: s2l_network