version: "3.7"

services:
  web:
    image: go-docker-webserver
    build: .
    ports:
      - "5000:5000"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      xpack.security.enabled: "false"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1